config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :show ] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
  

  # api related routes 
  # get 'api/v1/users/:id/posts', to: 'api/v1/posts#index'
  # get 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#index'
  # post 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#create'
  # namespace :api do
  #   namespace :v1 do
  #     resources :users do
  #       resources :posts, only: [:index] do
  #         resources :comments, only: [:index, :create]
  #       end
  #     end
  #   end
  # end
  namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts 
      end 
      resources :posts do
        resources :comments 
        resources :likes 
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # attr_accessor :email_confirmation

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  # associations
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :email, confirmation: true
  validates :postscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all

    render json: @users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      @users = User.order('id ASC')
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %>
  <h1 class="users font-bold text-3xl py-10 px-24 capitalize" >All Users </h1>
  <br>
  <ul class="pb-5 ">
    <% @users.each do |user| %>
      <li class="mb-4 mt-2 hover:text-white">
        <%= link_to user_path(user) do %>
          <%= render "common/user", user: user %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<section class="post-container px-8 hover:text-white">
  <%= render "common/user", user: @user %>
  <div>
    <div class="border px-4 py-4 my-4">
      <h2 class="bio text-xl font-bold">User Bio</h2>
      <br>
      <p><%= @user.bio %></p>
    </div>
    <ul class="border px-4 py-4">
      <% @user.recent_posts.each do |post|%>
        <%= link_to user_posts_path(@user, post) do %>
          <li class="border gap-3">
            <div class="gap-4 rounded-md">
              <h3 class="font-bold">Post #<%= post.id%></h3>
              <br>
              <div>
                <h4><%= post.title%></h4>
                <br>
                <p><%= post.text %></p>
                <div class="text-like text-right pr-2 pl-40 rounded-md">
                  <span>Comments: <%= post.commentscounter%>,</span>
                  <span>Likes: <%= post.likescounter%></span>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= link_to "See all posts", "/users/#{@user.id}/posts", class: "bg-slate-500 text-white mx-32 px-24 py-1 rounded shadow mt-5 hover:bg-slate-600 active:scale-105" %>
  </div>
</section>