config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :show ] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
  

  # api related routes 
  # get 'api/v1/users/:id/posts', to: 'api/v1/posts#index'
  # get 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#index'
  # post 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#create'
  # namespace :api do
  #   namespace :v1 do
  #     resources :users do
  #       resources :posts, only: [:index] do
  #         resources :comments, only: [:index, :create]
  #       end
  #     end
  #   end
  # end
  namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts 
      end 
      resources :posts do
        resources :comments 
        resources :likes 
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :increase_postscounter
  after_destroy :decrease_postscounter

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  # validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :commentscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likescounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # methods
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increase_postscounter
    author.increment!(:postscounter)
  end

  def decrease_postscounter
    author.decrement!(:postscounter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = User.find(params[:id]).posts

    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id]).includes(comments: [:author])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes([:author]).find(params[:id])
    @comments = @post.comments.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.commentscounter = 0
    @post.likescounter = 0
    if @post.save
      flash[:success] = 'Post Added Successfully'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Post could not be added'
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to user_posts_path, notice: 'Post was deleted'
    else
      flash.now[:error] = 'Error: Post not deleted'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<section class="hover:text-white px-8 py-8">
  <div class="gap-4 flex flex-row w-full">
    <div class="w-1/12">
      <%= image_tag "/images/kk1.png", atl: "#{@user.name}-avatar", class: "block w-[90px] h-24" %>
    </div>

    <div class="w-11/12 border flex-row flex rounded-md">
      <h3 class="name text-2xl w-1/2 font-bold tracking-wider leading-10 py-6 pl-6"><%= @user.name %></h3>
      <span class="w-1/2 flex justify-end px-4 pt-10">Number of posts <%= @user.postscounter %></span>
    </div>
  </div>
  <% if current_user.id == @user.id %>
    <%= link_to "Create Post", new_user_post_path, class: "uppercase bg-slate-600 text-slate-100 text-lg hover:bg-slate-500 active:scale-105 ml-auto px-3 py-1 rounded block w-2/5 mt-5 text-center" %>
  <% end %>
  <ul class="gap-3">
    <% @posts.each do |post| %>
      <li class="border list-none mt-4 hover:bg-slate-200 text-black rounded-md">
        <div class="gap-4 rounded-md">
          <h3 class="font-bold">Post #<%= post.id%></h3>
          <br>
          <div>
            <h4><%= link_to "#{post.title}", user_post_path(@user, post) %></h4>
            <br>
            <p><%= post.text %></p>
            <div class="text-like text-right pr-2 pl-40 rounded-md">
              <span>Comments: <%= post.commentscounter%>,</span>
              <span>Likes: <%= post.likescounter%></span>
              <% if can? :destroy, post %>
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
                  <%= button_to "Delete", user_post_path(@user, post), method: :delete, data: {confirm: "Do you want to delete the comment?" } %>
                </button>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
        <% post.comments.last(5).each do |comment| %>
          <ul class="py-2 px-3 rounded-md">
            <div>
              <span class="author text-lg text-cyan-700 "><%= comment.author.name %></span>:
              <span><%= comment.text %></span>
            </div>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: user_posts_path do |form|%>
  <%= form.text_field :title, class:"block w-full flex-1 border-black border-4 p-4 sm:text-sm", placeholder:"Title" %>
  <%= form.text_field :text, class:"mt-4 block w-full border-black border-4 p-4 sm:text-sm", placeholder:"Description" %>
  <div>
    <%= form.submit "Submit", class: "bg-slate-600 text-white rounded shadow px-3 py-1" %>
  </div>
<% end %>

app/views/posts/new_post.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: users_posts_path do |form|%>
    <div>
        <%= form.label :title %> <br>
        <%= form.text_field :title, placeholder:'title'%>
        <% @post.errors.full_messages_for(:title).each do |message|%>
            <p><%= message%></p>
        <% end %>
    </div>

    <div class="my-2">
        <%= form.label :text %> <br>
        <%= form.text_area :text, placeholder:'text'%>
        <% @post.errors.full_messages_for(:text).each do |message|%>
            <p><%= message%></p>
        <% end %>
    </div>

    <div>
       <%= form.submit "Submit ", class: "bg-blue-600 text-white rounded shadow px-3 py-1" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<section class="rounded-md hover:text-white px-8 py-8">
  <div class="border px-4 pt-4">
    <div class="justify-between flex">
      <h3 class="text-2xl">Post #<%= @post.id%> by <%=@post.author.name %></h3>
      <%= render 'common/likes', post:@post%>
    </div>
    <br>
    <%= form_with url: "/users/#{@post.author.id}/posts/#{@post.id}/likes" do |form|%>
      <%= form.submit "like", class: "bg-slate-600 text-white rounded shadow px-2 block ml-auto text-lg cursor-pointer"%>
    <% end %>
    <p class="pb-6 mt-5"><%= @post.text %></p>
  </div>
  <div class="border mt-6">
    <%= render partial: "common/comments", locals: { comment: @comment }%>
  </div>
  <%= link_to "Add comment", "/users/#{@post.author.id}/posts/#{@post.id}/comments/new", class: "px-3 py-1 bg-slate-600 rounded text-white mt-8 mb-2 w-1/5 block ml-auto"%>
</section>