config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :show ] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
  

  # api related routes 
  # get 'api/v1/users/:id/posts', to: 'api/v1/posts#index'
  # get 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#index'
  # post 'api/v1/users/:user_id/posts/:post_id/comments', to: 'api/v1/comments#create'
  # namespace :api do
  #   namespace :v1 do
  #     resources :users do
  #       resources :posts, only: [:index] do
  #         resources :comments, only: [:index, :create]
  #       end
  #     end
  #   end
  # end
  namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts 
      end 
      resources :posts do
        resources :comments 
        resources :likes 
      end
    end
  end
end

app/views/common/_comments.html.erb
<ul class="py-2 px-3 rounded-md">
  <% @comments.each do |comment|%>
    <div>
      <span class="author text-lg text-cyan-700 "><%= comment.author.name %></span>:
      <span><%= comment.text %></span>
      <% if can? :destroy, comment %>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
          <%= button_to "Delete", user_post_comment_path(@user, @post, comment), method: :delete, data: {confirm: "Do you want to delete the comment?" } %>
        </button>
      <% end %>
    </div>
  <% end %>
</ul>

app/views/common/_likes.html.erb
<div class="text-like text-right pr-2 pl-40 rounded-md">
   <span>Comments: <%= post.commentscounter%>,</span>
    <span>Likes: <%= post.likescounter%></span>
</div>

app/views/common/_post.html.erb
<div class="gap-4 rounded-md">
  <h3 class="font-bold">Post #<%= post.id%></h3>
  <br>
  <div>
    <h4><%= post.title%></h4>
    <br>
    <p><%= post.text %></p>
    <div class="text-like text-right pr-2 pl-40 rounded-md">
      <span>Comments: <%= post.commentscounter%>,</span>
      <span>Likes: <%= post.likescounter%></span>
    </div>
  </div>
</div>
 

app/views/common/_user.html.erb
<div class="gap-4 flex flex-row w-full">
  <div class="w-1/12">
    <%= image_tag "/images/kk1.png", atl: "#{user.name}-avatar", class: "block w-[90px] h-24" %>
  </div>

  <div class="w-11/12 border flex-row flex rounded-md">
    <h3 class="name text-2xl w-1/2 font-bold tracking-wider leading-10 py-6 pl-6"><%= user.name %></h3>
    <span class="w-1/2 flex justify-end px-4 pt-10">Number of posts <%= user.postscounter %></span>
  </div>
</div>